version: 2.1
orbs:
  auto-cancel: ganezasan/auto-cancel-workflow@dev:first
  orb-tools: circleci/orb-tools@7.3.0

executors:
  default:
    docker:
      - image: alpine:latest
jobs:
  job-1:
    executor: default
    steps:
      - run: sleep 120
  job-2:
    executor: default
    steps:
      - run: sleep 60
  failed-job:
    executor: default
    steps:
      - run: sleep 30 && exit 1

workflows:
  version: 2
  a-job-failed:
    jobs:
      - hold:
          type: approval
      - job-1:
          requires:
            - hold
      - job-2:
          requires:
            - hold
      - failed-job:
          requires:
            - hold
      - auto-cancel/auto-cancel:
          requires:
            - hold
          api_token: CIRCLE_TOKEN
          interval_seconds: 10
  all-jobs-success:
    jobs:
      - hold:
          type: approval
      - job-1:
          requires:
            - hold
      - job-2:
          requires:
            - hold
      - auto-cancel/auto-cancel:
          requires:
            - hold
          api_token: CIRCLE_TOKEN
          interval_seconds: 10
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: ganezasan/auto-cancel-workflow
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          ssh-fingerprints: 65:2b:cc:9d:a2:19:53:62:55:24:b5:96:d6:71:66:13
          tag: master
          use-git-diff: false
          static-release-type: patch
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master
  integration-tests_prod-release:
    jobs:
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          orb-name: ganezasan/auto-cancel-workflow
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-.*/
